services:
  api:
    build: .
    depends_on:
      - db
      - adminer
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - WDS_SOCKET_HOST=127.0.0.1 
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/api

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toto90
      POSTGRES_DB: slice-pizzeria

  adminer:
    image: adminer
    ports:
      - 8080:8080

