services:
  api:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - WDS_SOCKET_HOST=127.0.0.1 
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/api

