services:
  slice-pizzeria-api:
    container_name: slice-pizzeria-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - DB_HOST=slice-pizzeria-db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=toto90
      - DB_DATABASE=slice-pizzeria
      - SECRET_KEY=toto90
    #env_file:
    #  - .env
    ports:
      - 3000:3000
    depends_on:
      - slice-pizzeria-db
      - slice-pizzeria-adminer
    stdin_open: true
    tty: true

  slice-pizzeria-db:
    container_name: slice-pizzeria-db
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toto90
      POSTGRES_DB: slice-pizzeria
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:rw

  slice-pizzeria-adminer:
    container_name: slice-pizzeria-adminer
    image: adminer:5.2.1-fastcgi
    restart: unless-stopped
    ports:
      - 8080:8080
